### ISSUE TITLE
decompression error

### ISSUE THREAD

**Issue by arthuryxt** [OpenGene/repaq#1]
Hi, thanks for the tool! The compression ratio is IMPRESSIVE, down to 3.1%! But I got the following error using decompression... 
"
~/bin/repaq -d -i haha.rfq -o ha_1.fq -O ha_2.fq
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 404978952) > this->size() (which is 404978876)
Aborted (core dumped)
"

**Comment by sfchen** [comment]
Thanks, can you please send me a part of your data?

The program is not stable yet since it's being developed. I schedule to release the first version in 2 weeks.

**Comment by sfchen** [comment]
Can you please try the new version? re-compress it and re-decompress it.

The compression ratio is even improved.

**Comment by arthuryxt** [comment]
Thank you for your reply. The data I used was simulated and the fasta headers are not formatted in the way as bcl2fastq does, maybe this is the reason why it didn't work.

Yesterday, I downloaded the latest version of repaq, and used one our our real data. 
R1.fq looks like:
~~~~
@FCC1L04ACXX:6:1101:1736:1935#/1
NTTAATTCAAGATGAATTGGAGATTTAAATGTAAGACCTCAAACTATAAGAATGCTAGAAGAAAACATAGGAAAAACCATTCTGGACATC
+
BPJSS`c`[bbc]ecc]f]eaf_Z[S`agSSX`eX^Pb_Rc[be[c[ea[ac]eYceYe]_ehZbXGH\bRVW_HMT^`\HV\acaZaBB
@FCC1L04ACXX:6:1101:8253:9797#/1
TAAGGGTGAAGTTACGTGGGGAAGGGGAGTGCCAGCCTAGCTCAGGAAAATAATGAGTGAAAAAACAGGCAAGAGGACAGGTAATGTAGA
+
abbe`dacgggggiiifhhiihhiiiifhaffhiihiiiihhihiihhihfiihhgg`dggeeeccccccccccccccccc]`bdcbcdd
~~~~
and R2.fq looks like:
~~~~
@FCC1L04ACXX:6:1101:1736:1935#/2
TTGATTTTCATTTCTCTGGTGATTGGTGTTGATGAACATTTTTTCATATATTTTTTGAATTGTATGTCATCTTTTGGAAAGGGGTCATAC
+
aa_cac^Zecge`_fddeaR[bcdeXb`JJJ[`a^^Ib^[b^a^ebX^SIXa_eghFGHMMHNVVHM\b`M\`R``FMZ^Z]^FFK\_a]
@FCC1L04ACXX:6:1101:8253:9797#/2
TGTGGGAGAGAGCTGGTGGCAGGTAATTTAATTATGGGGGGCAGGTTTTTCCCATGCTGTTCTCATGATAGTAAATAAGTCTCATGAGAT
+
_b_ceeeegffgghiiffhiiii^eghiihhhihhhiiihcccccWbbcccccbccbcbcccdcddcccdbbcccddcccddcddccccb
~~~~

The size of the files (R1.fq, R2.fq, R1.fq.gz, R2.fq.gz, R1R1.rfq and R1R1.rfq.xz) are (13G, 13G, 38G, 38G, 41G and 22G).  Can the compression ratio due to the old-version of fasta header again?

Corrected (sorry for the wrong ordering): 
The size of the files (R1.fq.gz, R2.fq.gz, R1.fq, R2.fq, R1R1.rfq and R1R1.rfq.xz) are (13G, 13G, 38G, 38G, 41G and 22G).  Can the compression ratio due to the old-version of fasta header again?

**Comment by sfchen** [comment]
Do you mean the compressed data is bigger than the original file? For both gzip and repaq.

**Comment by arthuryxt** [comment]
Sorry!  
the plain file is 38G
gzip file is 14G
rfq file is 41G
rfq.zx file is 22G

**Comment by sfchen** [comment]
Your data are hard to compress since the quality bin number is too high.

**Comment by sfchen** [comment]
Can you upload the first 10000 lines of the R1 and R2 files?

**Comment by arthuryxt** [comment]
Thanks! Here they are:
[test_R1.fq.gz](https://github.com/OpenGene/repaq/files/2272927/test_R1.fq.gz)
[test_R2.fq.gz](https://github.com/OpenGene/repaq/files/2272928/test_R2.fq.gz)
