### ISSUE TITLE
is it possible make bcl2rfq in progress

### ISSUE THREAD

**Issue by BaconKwan** [OpenGene/repaq#10]
since new version of bcl2fastq exist many problems in practical applications, besides, fastp is an amazing utility and it has came into use in my pipelines. 

I guess it is a great work that we can develop an alternative tool in the very beginning of the analysis workflow. 

Once it works, maybe a new workflow of raw data processing standard is born.

**Comment by sfchen** [comment]
No plan yet, thanks.
