### ISSUE TITLE
round-trip is not identical

### ISSUE THREAD

**Issue by grst** [OpenGene/repaq#11]
On some fq files, the quality string is not preserved
in a round-trip conversion. In particular `;` or `:` gets replaced by `I`. 

One example line, first line is original: 
```
-BBDADFHHHHHHII?HHHIIII?EHEHCDHDHGFHHHEFHHHIECD/E?@FH1<@GEGH?GHH?@CC@?E1<D@FGH111G?CHF0CCEG?0<FFE0:F0=
+BBDADFHHHHHHII?HHHIIII?EHEHCDHDHGFHHHEFHHHIECD/E?@FH1<@GEGH?GHH?@CC@?E1<D@FGH111G?CHF0CCEG?0<FFE0IF0=
```

repaq-command
```
repaq -c -i original.fq -o original.fq.rfq
```

**Comment by sfchen** [comment]
Can you please upload a file, that I can test?

**Comment by grst** [comment]
Unfortunately, I got this file under protected access agreement. 
Feel free to reach out to me by email (mail at gregor-sturm.de) and we can try to find a solution.

**Comment by sfchen** [comment]
OK

**Comment by sfchen** [comment]
Should be already fixed
