### ISSUE TITLE
Consistency of repaq, and readiness for production

### ISSUE THREAD

**Issue by lebovic** [OpenGene/repaq#14]
Hi! We're considering using repaq due to the significant space savings, but have some concerns about lossless-ness. Some of the other issues (#11, #12, #13) seem to suggest that repaq isn't lossless, but there isn't enough detail on some (#12, #13) to determine the severity.

How production ready is repaq?

**Comment by lebovic** [comment]
@sfchen

**Comment by sfchen** [comment]
Actually my company has already used repaq for production since 2018.

But I will address these issues in about 2 months.

**Comment by sfchen** [comment]
addressed
